### ISSUE TITLE
Filtering taxonomies

### ISSUE THREAD

**Issue by phh** [stuttter/wp-term-order#10]
Sometimes not all taxonomies should be filtered. I had some issues with a taxonomy not being able to order by names due to wp-term-order.

Having a filter like the simple-page-ordering plugin would be neat. So you could easily enable/disable these:
`simple_page_ordering_is_sortable`
See: https://da.wordpress.org/plugins/simple-page-ordering/faq/

There is a filter for `wp_term_order_get_taxonomies` but its not used within the plugins `get_terms_orderby` filter or the `wp_ajax_reordering_terms` and `load-edit-tags.php` actions.

Having a check for sorting before enabling all of these would make it possible for developers to not always let the wp-term-order to take over the ordering og get_terms.

**Comment by benhuson** [comment]
Some of this issue has been fixed by the https://github.com/stuttter/wp-term-order/commit/399d2b3ac2dd86324e3a75d103cf33817d60154d commit.

I have also submitted a pull request #13 which disables the `get_terms_orderby` filter for taxonomies removed via the `wp_term_order_get_taxonomies` filter.

**Comment by JJJ** [comment]
Thanks @benhuson. Will be in the next release.

**Comment by benhuson** [comment]
Thanks @JJJ 👍
