### ISSUE TITLE
Test plugin with more recent WordPress version to update repository page

### ISSUE THREAD

**Issue by taeo920** [stuttter/wp-term-order#16]
While I know this plugin is perfectly compatible with the latest version of WordPress I have a client whose site must pass a fairly strict security audit. They will not allow plugins that have not been updated or tested since the latest version of WordPress.

If I can help to make this happen I would be very happy to do whatever it takes. There are several plugins that enable similar functionality as this but I know that yours is among the cleanest and most reliable. I use it on many sites. I'd hate to have to stop using it due to a technicality.

Thank you!

**Comment by timiwahalahti** [comment]
@JJJ any chances to update the "Tested up to" version? :) Thanks!

**Comment by JJJ** [comment]
Bumped to 0.1.5, including updated plugin headers and such.

Thanks!
