### ISSUE TITLE
Can't Change Order

### ISSUE THREAD

**Issue by RenegadeMonster** [stuttter/wp-term-order#2]
Not sure what I am doing wrong here, but I can't change the order for my terms.

I can drag and drop them to the order I want, but as soon as I visit an other page in the admin panel and come back to my custom taxonomy the terms are once again sorted by their ID.

I tried dragging them to where I wanted them, checking everything, and hitting apply to see if maybe it wasn't being saved.  No go, same result happens.

Next  tried editing each term and changing the order values to 1 through 6 to place them in the order I wanted and saving them.  This didn't work either.  For example, one term I change from 1 to 4 then save it.  Go right back in to edit it and its 1 again.

**Comment by RenegadeMonster** [comment]
Looking at other custom taxonomies I have and trying to change order I have found that the issue is the order isn't being saved.

The order numbers are numbered in order of their ID.  Any  changes made to this field are not saved and it reverts back to where it was.

Could this be a compatibility issue with the "Custom Post Type UI" plugin that I use to create custom post types and taxonomies?

**Comment by ronalfy** [comment]
I've noticed the same behavior in child terms. They aren't saving.

**Comment by johnjamesjacoby** [comment]
This will get fixed as part of the imminent fix for #1.

Thanks for the issue!
