### ISSUE TITLE
Update WP Plugin Directory page with latest version of this plugin

### ISSUE THREAD

**Issue by matthewmcvickar** [stuttter/wp-term-order#24]
This repository indicates the plugin is at version 2.0.0, but [the WordPress Plugins Directory page has version 1.0.0](https://wordpress.org/plugins/wp-term-order/) and warns that the plugin hasn't been updated in three years. Can you update the directory version with the latest version here?

**Comment by benoitchantre** [comment]
Ping @JJJ

**Comment by ethanclevenger91** [comment]
There are kind of major bugs included here that do not exist in the version on the WP repo, including #11

**Comment by timiwahalahti** [comment]
@JJJ any news? Can we help you to get this done?

**Comment by timiwahalahti** [comment]
@JJJ sorry to bother again. Could we get these few small updates done to this great plugin? Or would you be open for handing contributor role for few individuals that are keen to keep this plugin updated?

**Comment by JJJ** [comment]
Going to do this today.

**Comment by JJJ** [comment]
2.1.0 released & pushed to WordPress.org 🫶

**Comment by timiwahalahti** [comment]
Thank you JJJ! ❤️
