### ISSUE TITLE
Migrate to new term meta?

### ISSUE THREAD

**Issue by lkraav** [stuttter/wp-term-order#3]
Hi. Instead of altering schema, are there plans to use the new core term meta? cc @JoonasVaino

**Comment by phh** [comment]
+1

**Comment by rasmustaarnby** [comment]
Maybe it would make more sense to use term_order, which I guess is meant only for ordering the terms in a taxonomy. 

https://core.trac.wordpress.org/browser/tags/4.5.2/src/wp-includes/taxonomy.php#L2458

**Comment by johnjamesjacoby** [comment]
I've considered porting this to metadata, but ordering results by the join will reduce the speediness and scalability pretty significantly once there are lots of terms and metadata.

FWIW, altering the schema does not hurt anything alone. WordPress does not complain, nor will any other plugins or themes. The only potential problem comes from the eventuality of WordPress supporting this natively, and this plugin colliding with those efforts. In that case, I work closely with core development initiatives to ensure no breakage occurs to users of my plugins.

**Comment by JJJ** [comment]
@petertoi would you be interested in collaborating?

I think it would be neat to have support for both approaches

* What's here for performance, where people are OK with altering the schema
* Whet you have for compatibility, where people are not OK with altering the schema

Then we can maintain everything in one place! Thoughts?

**Comment by petertoi** [comment]
Hey @JJJ,

Sounds like fun. Count me in for sure.

How do you want to start?

**Comment by JJJ** [comment]
Awesome!

I suppose we should both get familiar with how our forks have diverged, find a way to gracefully merge them, and invent a switching mechanism to allow switching between them?

**Comment by petertoi** [comment]
Sounds good to me. I'll refamiliarize myself with the code base and touch base next week to keep the conversation going. Cheers!
