### ISSUE TITLE
Consider adding a hook in WP_Term_Order->set_term_order() to help with WPML compatibility?

### ISSUE THREAD

**Issue by benhuson** [stuttter/wp-term-order#6]
Hi JJJ,

I'm working with WP Term Order on a WPML site and I'd like to sync the order of translated pages with the default language.

At the moment I can't see an obvious way to hook into when a term order is updated to sync the change to the translated terms.

Would you consider adding an action hook in `WP_Term_Order->set_term_order()` passing the same parameters so that when a term order is updated, the changes can be applied to translated terms?

I would submit a PR but it's only one line and I thought you might want to decide on the name for the action hook - happy to if you want me to 😀

Ben

**Comment by johnjamesjacoby** [comment]
Hey @benhuson! Send over a PR if you can; I trust it'll be okay, and I'll be gentle afterwards if I think it needs anything more. :)

**Comment by johnjamesjacoby** [comment]
@benhuson is this something you're still interested in?

**Comment by benhuson** [comment]
@johnjamesjacoby Hi. Yes, I've just been busy on other things and not come back to it.

Will submit a PR when I'm back on the WPML project for which I needed it, probably sometime next week.

**Comment by JJJ** [comment]
Merged. Will be in the next release. Thank you!
